COMMENT @***************************************************************

	file generated by OS/90 nim2pc utility

************************************************************************@
fdata	segment
include	geos.def
include	graphics.def
include	font.def
UseDriver	Internal/fontDr.def
;StartFont  label   byte
	db	"BSWF"				;signature
	db	0				;minor
	db	1				;major
	dw	EndHead - StartHead		;header size

StartHead	label	byte
;	dw	FID_BERKELEYt			;font id
	dw	FID_BERKELEY			;font id
	dw	FM_BITMAP			;maker
	db	129				;family
	char	"Berkeley", 12 dup (0)		;face name

	dw	berkeleyBitmapStart-StartHead+2
	dw	berkeleyBitmapEnd-StartHead+2
	dw	0				;no outlines
	dw	0

berkeleyBitmapStart	label	byte
	byte	0x0				;styles
	WBFixed	<0,9>				;pointsize
;	FontCharSet 0;character set
	word	berkeley_09EndData-berkeley_09StartData
	dword	offset berkeley_09StartData

	byte	0x0				;styles
	WBFixed	<0,10>				;pointsize
;	FontCharSet 0;character set
	word	berkeley_10EndData-berkeley_10StartData
	dword	offset berkeley_10StartData

	byte	0x0				;styles
	WBFixed	<0,12>				;pointsize
;	FontCharSet 0;character set
	word	berkeley_12EndData-berkeley_12StartData
	dword	offset berkeley_12StartData

	byte	0x0				;styles
	WBFixed	<0,14>				;pointsize
;	FontCharSet 0;character set
	word	berkeley_14EndData-berkeley_14StartData
	dword	offset berkeley_14StartData

	byte	0x0				;styles
	WBFixed	<0,18>				;pointsize
;	FontCharSet 0;character set
	word	berkeley_18EndData-berkeley_18StartData
	dword	offset berkeley_18StartData

berkeleyBitmapEnd	label	byte

EndHead  label   byte

fdata	ends
fontgroup group fdata ,berkeley_09Seg ,berkeley_10Seg ,berkeley_12Seg ,berkeley_14Seg ,berkeley_18Seg

include berkeley_09.def
include berkeley_10.def
include berkeley_12.def
include berkeley_14.def
include berkeley_18.def

;EndData label byte
end
